WIP: Add PostgreSQL support
lava-xyz/sibyls pull request #17
Opened 2024-07-01 22:51 UTC by mousetrail

2024-07-08 01:34 UTC, Tibo-lg requested changes
This does not compile for me, before reviewing the code it'd be nice that it compiles. I think you probably forgot to commit `schema.rs`.

2024-07-08 20:10 UTC, mousetrail commented
@Tibo-lg Good catch! I added the missing files

2024-07-10 05:08 UTC, Tibo-lg commented on sibyls/src/error.rs
> +    SledDatabaseError(#[from] sled::Error),
Or maybe another way would be to use generics, so that `DatabaseError` takes a generic parameter.

2024-07-10 05:15 UTC, Tibo-lg commented on sibyls/src/oracle/error.rs
> +    Error(String),
These two don't seem to be used (maybe it's just my IDE who can't find the use?)

2024-07-10 05:19 UTC, Tibo-lg commented on sibyls/src/oracle/pricefeeds/gateio.rs
> +    /* TODO fix this test
?

2024-07-11 01:31 UTC, mousetrail commented on sibyls/src/db.rs
> +                if scheme == &"sled" {
Could you please elaborate on how to do it in a non-hacky way? I think using the command line to pick which database to use is pretty straightforward.

Regarding traits, I tried using a trait to begin with in the earlier commits but I couldn't figure out how to use it properly. I did it like this: 
```rust
pub struct Oracle {
    pub oracle_config: OracleConfig,
    asset_pair_info: AssetPairInfo,
    pub event_database: EventStorage,
    keypair: KeyPair,
}
```
Like this I get this error
```
error[E0782]: trait objects must include the `dyn` keyword
  --> sibyls/src/oracle/mod.rs:20:25
   |
20 |     pub event_database: EventStorage,
   |                         ^^^^^^^^^^^^
   |
```
When I add the `dyn` keyword to `EventStorage` I get this error
```
error[E0277]: the trait bound `dyn EventStorage: Clone` is not satisfied
  --> sibyls/src/oracle/mod.rs:20:5
   |
16 | #[derive(Clone)]
   |          ----- in this derive macro expansion
...
20 |     pub event_database: dyn EventStorage,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `dyn EventStorage`
   |
```
This is why I used an enum since it all ended up working fine. Please suggest where I can find more information on how to properly use traits in this case.

2024-07-11 01:32 UTC, mousetrail commented on sibyls/src/db.rs
> +struct NewEvent {
This is how they suggested to do it in the Diesel documentation, if there's a better way please let me know.

2024-07-11 01:58 UTC, Tibo-lg commented on sibyls/src/db.rs
> +                if scheme == &"sled" {
You need to use generics for it to work properly. So you would have something like:
```rust
pub struct Oracle<Db: EventDatabase> {
  ...
  pub event_database: Db,
}
```

Where `EventDatabase` is the trait.

2024-07-11 01:59 UTC, Tibo-lg commented on sibyls/src/db.rs
> +struct NewEvent {
I'm not familiar with diesel, can you point to the documentation you're referring to?

2024-07-11 02:00 UTC, Tibo-lg commented on sibyls/src/db.rs
> +                if scheme == &"sled" {
As for the CLI parsing, I think what would be good would be to have an enum, but used only for parsing the parameter. `clap` should be able to parse the enum directly. Ideally also you'd want to use `clap` conditionals so you only need to provide parameters for pg when using the pg option.

2024-07-12 23:55 UTC, mousetrail commented on sibyls/src/db.rs
> +                if scheme == &"sled" {
Thank you for the tip. After starting to implement it as a trait, I realized it would require restructuring the entire project just to make it compile. This affects almost every function. Therefore, I think using a trait is a bit beyond the scope of this PR because it's very big as it is and it will be difficult to review. 

Let's focus on functionality first and I believe that a trait can be implemented in a separate PR.

2024-07-17 03:50 UTC, mousetrail commented on sibyls/src/db.rs
> +struct NewEvent {
Oh, you're right actually, I deleted it.

2024-07-18 05:48 UTC, Tibo-lg commented on sibyls/src/oracle/error.rs
> +    SibylsError(#[from] SibylsError),
Is this used anywhere?

2024-07-18 05:48 UTC, Tibo-lg commented on sibyls/src/oracle/error.rs
> +    SibylsError(#[from] SibylsError),
Note the one above is also not used somehow, not due to this PR, but it might be cleaner to remove it at the same time.

2024-07-19 23:25 UTC, mousetrail commented on sibyls/src/oracle/error.rs
> +    SibylsError(#[from] SibylsError),
This error is used right here:
https://github.com/lava-xyz/sibyls/pull/17/files#diff-c15246dda8378a400b0b083d5f9082473aeaaabfe3766b1d4a8614a13c3b7d1cR37

2024-07-19 23:27 UTC, mousetrail commented
@shehzanmaredia Sounds good, I will make a GitHub issue about the generics refactoring.

2024-07-20 00:41 UTC, mousetrail commented
This is the issue I made: https://github.com/lava-xyz/sibyls/issues/19

2024-07-22 00:15 UTC, merged